name: bcl
favicon: null
layout_spectrum: 0.7028748395387083
typography_spectrum: 0.9283209147397429
title: BENZ CADILLAC LIMOUSINE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#3C493F'
    - '#7E8D85'
    - '#B3BFB8'
    - '#F0F7F4'
    - '#A2E3C4'
  brandStrength: 0.6985480992589146
  lightness: 0.06435203365981579
  saturation: 0.35623000166378915
  rhythmicContrast: 0.5999455994460732
purpose: []
